// ============================================
// RESOURCE MODEL - defines learning resource data
// ============================================

const mongoose = require('mongoose');

const resourceSchema = new mongoose.Schema({
  // Resource title
  title: {
    type: String,
    required: [true, 'Title is required'],
    trim: true,
    maxlength: [100, 'Title cannot exceed 100 characters']
  },

  // Full description of the resource
  description: {
    type: String,
    required: [true, 'Description is required'],
    maxlength: [2000, 'Description cannot exceed 2000 characters']
  },

  // Subject category
  subject: {
    type: String,
    required: [true, 'Subject is required'],
    enum: [
      'Mathematics',
      'Science',
      'Technology',
      'Programming',
      'History',
      'Language',
      'Arts',
      'Business',
      'Other'
    ]
  },

  // Type of resource
  type: {
    type: String,
    required: [true, 'Resource type is required'],
    enum: ['PDF', 'Video', 'Article', 'Tutorial', 'Link', 'Notes']
  },

  // External URL link
  url: {
    type: String,
    default: ''
  },

  // Uploaded file path (local disk path)
  file: {
    type: String,
    default: ''
  },

  // Persistent binary file data in MongoDB (ensures files survive container redeployments)
  fileData: {
    type: Buffer,
    select: false
  },

  fileContentType: {
    type: String,
    default: ''
  },

  fileOriginalName: {
    type: String,
    default: ''
  },

  // Thumbnail image
  thumbnail: {
    type: String,
    default: ''
  },

  // Who uploaded this resource
  uploadedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },

  // How many times this was viewed
  views: {
    type: Number,
    default: 0
  },

  // Users who saved/liked this resource
  saves: [{
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  }],

  // Anonymous guest likes tracked by persistent guest UUID or IP
  guestLikes: [{
    type: String,
    default: []
  }],

  // Is this resource featured on homepage
  featured: {
    type: Boolean,
    default: false
  },

  // Extracted text content from the file or URL/description for AI tutoring
  content: {
    type: String,
    default: ''
  },

  // Verified, objective short description generated by backend breakdown
  shortDescription: {
    type: String,
    default: ''
  },

  // Key educational topics and concepts identified in the resource
  keyTopics: [{
    type: String
  }],

  // Document chunks for RAG-based retrieval
  chunks: {
    type: [{
      index: { type: Number },
      text: { type: String },
      wordCount: { type: Number }
    }],
    select: false,
    default: []
  },

  // AI-generated summary of the uploaded notes/document
  chunkSummary: {
    type: String,
    default: ''
  }

}, {
  timestamps: true
});

module.exports = mongoose.model('Resource', resourceSchema);
